[window]
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "full"
startup_mode = "Maximized"

[font]
normal.family = "SauceCodePro NF"  # Changed to match installed font
bold.family = "SauceCodePro NF"  # Changed to match installed font
italic.family = "SauceCodePro NF"  # Changed to match installed font
bold_italic.family = "SauceCodePro NF"  # Changed to match installed font
size = 12
italic.style = "Regular"
bold_italic.style = "Bold"
# Tokyo Night theme colors
[colors]
# Default colors
primary.background = "#1a1b26"  # Tokyo Night background
primary.foreground = "#c0caf5"  # Tokyo Night foreground

# Normal colors
normal.black   = "#15161e"
normal.red     = "#f7768e"
normal.green   = "#9ece6a"
normal.yellow  = "#e0af68"
normal.blue    = "#7aa2f7"
normal.magenta = "#bb9af7"
normal.cyan    = "#7dcfff"
normal.white   = "#a9b1d6"

# Bright colors
bright.black   = "#414868"
bright.red     = "#f7768e"
bright.green   = "#9ece6a"
bright.yellow  = "#e0af68"
bright.blue    = "#7aa2f7"
bright.magenta = "#bb9af7"
bright.cyan    = "#7dcfff"
bright.white   = "#c0caf5"

# Selection colors
selection.text = "#c0caf5"
selection.background = "#28344a"

# Cursor colors
cursor.text = "#1a1b26"
cursor.cursor = "#c0caf5"

# Indexed Colors
indexed_colors = [
  { index = 16, color = "#ff9e64" },
  { index = 17, color = "#db4b4b" }
]

[cursor]
style.shape = "Block"
style.blinking = "On"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Block"
