# alacritty.toml
[window]
opacity = 1.0                # Fully opaque (no background-opacity in original)
decorations = "none"          # Matches: window-decoration = none
blur = false                  # Matches: background-blur = false
[font]
size = 20.0                   # Matches: font-size = 18
normal.family = "Iosevka"  # Matches: font-family
[colors]
# Gruber Darker theme
primary.background = "#181818"
primary.foreground = "#e4e4ef"
normal.black   = "#181818"
normal.red     = "#f43841"
normal.green   = "#73c936"
normal.yellow  = "#ffdd33"
normal.blue    = "#96a6c8"
normal.magenta = "#9e95c7"
normal.cyan    = "#95a99b"
normal.white   = "#e4e4ef"
bright.black   = "#52494e"
bright.red     = "#ff4f58"
bright.green   = "#73c936"
bright.yellow  = "#ffdd33"
bright.blue    = "#96a6c8"
bright.magenta = "#cc8c3c"
bright.cyan    = "#95a99b"
bright.white   = "#f4f4ff"