[window]
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "full"
startup_mode = "Maximized"

[font]
normal.family = "Iosevka"
bold.family = "Iosevka"
italic.family = "Iosevka"
bold_italic.family = "Iosevka"
size = 14

[colors]
# Default colors (match Vim's Normal bg/fg)
primary.background = "#000000"  # Vim's Normal bg
primary.foreground = "#e0def4"  # Vim's Normal fg

# Normal colors (match terminal_ansi_colors in Vim)
normal.black   = "#26233a"      # Overlay (darkest UI element)
normal.red     = "#eb6f92"      # Love (error highlights)
normal.green   = "#31748f"      # Pine (strings, keywords)
normal.yellow  = "#f6c177"      # Gold (numbers, booleans)
normal.blue    = "#9ccfd8"      # Foam (functions, types)
normal.magenta = "#c4a7e7"      # Iris (special chars, markup)
normal.cyan    = "#ebbcba"      # Rose (operators, delimiters)
normal.white   = "#e0def4"      # Text (foreground)

# Bright colors (lighter variants)
bright.black   = "#6e6a86"      # Muted (comments, line numbers)
bright.red     = "#eb6f92"      # Love (bright)
bright.green   = "#31748f"      # Pine (bright)
bright.yellow  = "#f6c177"      # Gold (bright)
bright.blue    = "#9ccfd8"      # Foam (bright)
bright.magenta = "#c4a7e7"      # Iris (bright)
bright.cyan    = "#ebbcba"      # Rose (bright)
bright.white   = "#e0def4"      # Text (bright)

# Cursor & Selection (match Vim's Visual mode)
cursor.text    = "#191724"      # Base bg
cursor.cursor  = "#e0def4"      # Text fg
selection.text = "#e0def4"      # Text fg
selection.background = "#403d52" # Vim's Visual mode bg
