[username]
style_user = "#c4a7e7 bold"  # iris
style_root = "#eb6f92 bold"  # love
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "@[$hostname](bold #31748f) "  # pine
trim_at = "."
disabled = false

[character]
success_symbol = "[❯](bold #e0def4)"  # text
error_symbol = "[✗](bold #eb6f92) "   # love

[directory]
read_only = ""  # no lock icon
truncation_length = 10
truncate_to_repo = true
style = "bold #31748f"  # pine

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold #f6c177"  # gold

[docker_context]
disabled = true

[git_branch]
symbol = ""  # no icon
format = "[git:$branch]($style) "
style = "bold #9ccfd8"  # foam
