#format = """
#[╭─user───❯](bold blue) $username
#[┣─system─❯](bold yellow) $hostname
#[┣─project❯](bold red) $directory$rust$git_branch$git_state$git_status$package$golang$terraform$docker_context$python$docker_context$nodejs
#[╰─cmd────❯](bold green)
#"""
[rust]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[terraform]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true


# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
#add_newline = true
success_symbol = "[❯](bold green)"     # The "success_symbol" segment is being set with the color "bold green"
error_symbol = "[❯](bold red)"         # The "error_symbol" segment is being set  with the color "bold red"

#  
# configure directory
[directory]
read_only = ""
truncation_length = 5 
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[git_branch]
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)" 
modified = "[${count}+](yellow)" 
deleted =  "[${count}-](red)" 
conflicted =  "[${count}~](red)" 
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)" 
staged = "[${count}+](green)" 

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"	
revert = "revert"	
cherry_pick = "cherry"
bisect = "bisect"	
am = "am"	
am_or_rebase = "am/rebase"

[hg_branch]
symbol = " "
